### ISSUE TITLE
跪求重新维护hexo white主题

### ISSUE THREAD

**Issue by huoranger** [FuShaoLei/wheel#1]
太喜欢white主题了，希望能够重新维护

**Comment by FuShaoLei** [comment]
@Coder-itCheng 谢谢你，朋友，这个项目已经两年没有维护了，没想到还有人挂念，又勾起了我许多关于此项目的美好回忆，以后我也会找时间去维护这款主题的，再次谢谢你的支持！

**Comment by huoranger** [comment]
哈哈哈，期待期待



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月29日 22:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [FuShaoLei/wheel] 跪求重新维护hexo white主题 (Issue #1) |

@Coder-itCheng 谢谢你，朋友，这个项目已经两年没有维护了，没想到还有人挂念，又勾起了我许多关于此项目的美好回忆，以后我也会找时间去维护这款主题的，再次谢谢你的支持！

**Comment by FuShaoLei** [comment]
@huoranger white主题现在重新开始维护了，最新修改都放在了dev分支，欢迎查看😁
